# Generated by Django 3.2.8 on 2023-02-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_internship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
